// Mocks generated by Mockito 5.4.0 from annotations
// in imageshowcase/test/features/search/data/repositories/search_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:imageshowcase/features/search/data/datasources/search_data_sources.dart'
    as _i3;
import 'package:imageshowcase/features/search/data/models/image_showcase_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeImageShowcaseModel_0 extends _i1.SmartFake
    implements _i2.ImageShowcaseModel {
  _FakeImageShowcaseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchDataSources].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchDataSources extends _i1.Mock implements _i3.SearchDataSources {
  MockSearchDataSources() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ImageShowcaseModel> fetchImage(String? searchText) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchImage,
          [searchText],
        ),
        returnValue:
            _i4.Future<_i2.ImageShowcaseModel>.value(_FakeImageShowcaseModel_0(
          this,
          Invocation.method(
            #fetchImage,
            [searchText],
          ),
        )),
      ) as _i4.Future<_i2.ImageShowcaseModel>);
}
